// SPDX-License-Identifier: Apache-2.0
'use strict';

const { bandVerdict, round } = require('./stats');
const { EFFECT_FLOOR } = require('../config');

// Revision drift — the fifth report type (spec 009, Report #006).
//
// Every other report type holds the skill text fixed and moves something
// underneath it: the model release (#001, #003), the vendor surface (#002), the
// capability tier (#004), the axes and the price (#005). This one inverts the
// design. The substrate is held still — same model, same provider, same surface,
// same suite, same fixed judge, same sampling — and the SKILL'S OWN TEXT moves,
// from the revision a report pinned to the revision upstream ships today.
//
// This module holds the report type's LANGUAGE as code rather than as
// hand-written page copy. That is deliberate: the fairness rule below is the one
// a measurement project is most tempted to apply in one direction only, and a
// rule that lives in prose cannot be gated before the run that would tempt it.

// ── the cell headline ────────────────────────────────────────────────────────
// A summary of the per-case band-overlap verdicts, worded about the REVISION.
// The release-drift headline says "the skill is measurably weaker", which is a
// sentence about a skill under a moving model. Here the model is the control.
function revisionHeadline(perCase) {
  const reg = perCase.filter((r) => r.verdict === 'regression').length;
  const imp = perCase.filter((r) => r.verdict === 'improvement').length;
  const s = (n) => (n === 1 ? '' : 's');
  if (reg && imp) {
    return `MIXED — the revision improved ${imp} case${s(imp)} and regressed ${reg} on non-overlapping bands.`;
  }
  if (reg) {
    return `REVISION REGRESSED — ${reg} case${s(reg)} scored lower under the current upstream text (bands do not overlap).`;
  }
  if (imp) {
    return `REVISION IMPROVED — ${imp} case${s(imp)} scored higher under the current upstream text (bands do not overlap); none regressed.`;
  }
  return 'WITHIN NOISE — the revision moved no case beyond its confidence band; the pinned text and the current text measure the same.';
}

// Classification word for a cell, from its headline. Kept separate so a caller
// can branch on the class without parsing prose.
function revisionClass(perCase) {
  const h = revisionHeadline(perCase);
  return h.split(' —')[0];
}

// ── the fairness sentence ────────────────────────────────────────────────────
// Spec 009 § Fairness, clauses 1 and 4. Where a revision IMPROVED a skill, the
// published #005 figure understates the pack a reader can install today; where it
// REGRESSED one, #005 overstates it. Both sentences are generated by the same
// function, from the same template, so the disclosure cannot quietly become a
// one-directional courtesy — the symmetry is a property of the code, and the
// gate asserts it.
//
// A cell within noise gets NO sentence. #005's figure stands unamended, because
// nothing was measured that would amend it, and manufacturing a hedge for a null
// result is how a report launders noise into a finding.
function fairnessSentence({ slug, classification, report005Delta, measuredDelta }) {
  const cls = String(classification || '');
  if (cls !== 'REVISION IMPROVED' && cls !== 'REVISION REGRESSED') return null;
  const improved = cls === 'REVISION IMPROVED';
  const direction = improved ? 'understates' : 'overstates';
  const d = (n) => (n == null ? 'n/a' : (n >= 0 ? '+' : '') + Number(n).toFixed(3));
  return `Report #005 measured ${slug} at ${d(report005Delta)} on the text it had pinned. `
    + `Report #006 measures the current upstream revision at ${d(measuredDelta)} on the same substrate and the same suite. `
    + `#005's published figure therefore ${direction} the pack upstream ships today for this skill, `
    + `and is amended by this report rather than corrected in place.`;
}

// ── per-cell scoping disclosures ─────────────────────────────────────────────
// Spec 009 AC-10. One cell in Report #006 measures something other than what its
// upstream author changed it to do, and the reader looking at that row is the
// reader who needs to be told.
const SCOPING_NOTES = {
  'git-workflow-and-versioning':
    'This revision changes the frontmatter `description:` line. In a skill runtime a description is a '
    + 'routing trigger: it decides whether the skill loads, and never reaches the model as guidance. '
    + 'Driftproof makes no routing decision — it always injects the skill, and passes the whole file, '
    + 'frontmatter included, as the system prompt. This cell therefore measures the revision as added '
    + 'context and cannot measure it as a trigger.',
};
function scopingNote(slug) {
  return SCOPING_NOTES[slug] || null;
}

// ── the baseline-reproduction control ────────────────────────────────────────
// Spec 009 AC-6, and the thing that makes the free pinned arm honest.
//
// Report #006 reuses #005's receipts as the pinned-text arm. That is valid only
// if the substrate has not moved, and `run.model_release_date` is null on every
// #005 receipt, so id equality is the only version evidence a receipt carries. A
// provider that re-points a concrete id at a new snapshot is invisible to it.
//
// It does not have to be. Every fresh run emits a BASELINE arm: the same cases,
// the same substrate, and no skill text at all. The revision cannot touch it by
// construction, so comparing the fresh baseline against the reused receipt's
// baseline re-measures exactly the thing id equality could not prove — at no
// extra cost, because that arm is already paid for.
//
// A cell whose baselines do not reproduce is NOT MEASURED. The reuse is a tested
// prediction, not an assumption the report asks the reader to grant.
function baselineBands(receipt) {
  const out = {};
  for (const c of receipt.results.cases) {
    if (c.mode !== 'baseline') continue;
    out[c.id] = { mean: c.mean != null ? c.mean : c.score, stddev: c.stddev || 0 };
  }
  return out;
}

function baselineControl(reused, fresh) {
  const A = baselineBands(reused);
  const B = baselineBands(fresh);
  const ids = [...new Set([...Object.keys(A), ...Object.keys(B)])];

  const perCase = ids.map((id) => {
    const before = A[id] || null;
    const after = B[id] || null;
    if (!before || !after) return { id, before, after, delta: null, moved: false, missing: true };
    const delta = round(after.mean - before.mean);
    // The same rule the study uses everywhere else: band separation AND the
    // effect floor. A baseline that wobbles inside its band has not moved.
    const raw = bandVerdict(before.mean, before.stddev, after.mean, after.stddev);
    const separated = raw === 'regression' || raw === 'improvement';
    return { id, before, after, delta, moved: separated && Math.abs(delta) >= EFFECT_FLOOR, missing: false };
  });

  const movedCases = perCase.filter((r) => r.moved);
  const missing = perCase.filter((r) => r.missing);
  const reproduced = movedCases.length === 0 && missing.length === 0;
  const aggDelta = round(
    (fresh.comparison && fresh.comparison.baseline_score != null ? fresh.comparison.baseline_score : 0)
    - (reused.comparison && reused.comparison.baseline_score != null ? reused.comparison.baseline_score : 0),
  );

  return {
    reproduced,
    blocked: !reproduced,
    verdict: reproduced ? 'MEASURED' : 'NOT MEASURED',
    moved_cases: movedCases.map((r) => r.id),
    missing_cases: missing.map((r) => r.id),
    aggregate_baseline_delta: aggDelta,
    floor: EFFECT_FLOOR,
    // THE CONTROL PROVES NON-REPRODUCTION. IT CANNOT SAY WHY. These strings used
    // to read 'the substrate moved' and 'the substrate held still' — a cause,
    // asserted by a comparison that measures two baseline arms and nothing else.
    // A 120-call stability probe then found generation-level sampling noise large
    // enough to account for every gap this control saw, with no substrate movement
    // required, and the report page retracted the claim while three committed
    // control records still carried it (approval finding F-009-N). Reason strings
    // only: no score, sample, hash or verdict changed with this edit.
    reason: reproduced
      ? 'the fresh baseline reproduces the reused receipt\'s baseline within the band and the floor, so the pinned-arm reuse stands for this cell'
      : `the fresh baseline does not reproduce the reused receipt's baseline (${movedCases.length} case(s) moved beyond the band and the ${EFFECT_FLOOR} floor${missing.length ? `, ${missing.length} case(s) absent on one side` : ''}) — the reused pinned arm is not comparable to the fresh arm, so revision drift cannot be separated from whatever else changed in this cell; the control establishes non-reproduction and does not identify a cause`,
    perCase,
  };
}

module.exports = {
  revisionHeadline, revisionClass, fairnessSentence, scopingNote, baselineControl,
};
